import type { TaskCategory, TaskSubject } from "./types";

export interface TaskPreset {
  title: string;
  subject: TaskSubject;
  category: TaskCategory;
  frequency: string;
  species?: string[];
}

export interface TaskPresetGroup {
  title: string;
  emoji: string;
  description: string;
  presets: TaskPreset[];
}

export const TASK_PRESET_GROUPS: TaskPresetGroup[] = [
  {
    title: "Household Operations",
    emoji: "🐈",
    description: "Routine care, chores, patrols, supplies, and domestic order.",
    presets: [
      {
        title: "Serve Breakfast",
        subject: "pet",
        category: "household",
        frequency: "1 day",
      },
      {
        title: "Conduct House Inspection",
        subject: "human",
        category: "household",
        frequency: "1 day",
      },
      {
        title: "Vacuum Enemy Territory",
        subject: "human",
        category: "household",
        frequency: "1 week",
      },
      {
        title: "Refresh Sleeping Quarters",
        subject: "pet",
        category: "household",
        frequency: "1 week",
      },
      {
        title: "Laundry Containment Protocol",
        subject: "human",
        category: "household",
        frequency: "1 week",
      },
      {
        title: "Restock Treat Inventory",
        subject: "pet",
        category: "household",
        frequency: "1 week",
      },
    ],
  },
  {
    title: "Human Wellness",
    emoji: "🌿",
    description: "Hydration, medication, mobility, rest, appointments, and recovery.",
    presets: [
      {
        title: "Exit Bed Successfully",
        subject: "human",
        category: "wellness",
        frequency: "1 day",
      },
      {
        title: "Drink Water",
        subject: "human",
        category: "hydration",
        frequency: "4 hours",
      },
      {
        title: "Take Medication",
        subject: "human",
        category: "medication",
        frequency: "1 day",
      },
      {
        title: "Stretch Human Limbs",
        subject: "human",
        category: "movement",
        frequency: "1 day",
      },
      {
        title: "Attend Medical Appointment",
        subject: "human",
        category: "wellness",
        frequency: "1 mon",
      },
      {
        title: "Take Recovery Nap",
        subject: "human",
        category: "wellness",
        frequency: "1 day",
      },
      {
        title: "Get Fresh Air",
        subject: "human",
        category: "wellness",
        frequency: "1 day",
      },
      {
        title: "Complete Morning Routine",
        subject: "human",
        category: "wellness",
        frequency: "1 day",
      },
      {
        title: "Apply Biofreeze",
        subject: "human",
        category: "wellness",
        frequency: "1 day",
      },
      {
        title: "Schedule Massage",
        subject: "human",
        category: "wellness",
        frequency: "1 mon",
      },
    ],
  },
  {
    title: "Work & Productivity",
    emoji: "💻",
    description: "Job search, coding, security study, tickets, testing, and deployments.",
    presets: [
      {
        title: "Apply for Job",
        subject: "human",
        category: "work",
        frequency: "1 day",
      },
      {
        title: "Update Resume",
        subject: "human",
        category: "work",
        frequency: "1 week",
      },
      {
        title: "Attend Meeting",
        subject: "human",
        category: "work",
        frequency: "1 day",
      },
      {
        title: "Complete Coding Session",
        subject: "human",
        category: "work",
        frequency: "1 day",
      },
      {
        title: "Fix Bug",
        subject: "human",
        category: "work",
        frequency: "1 day",
      },
      {
        title: "Review Pull Request",
        subject: "human",
        category: "work",
        frequency: "1 day",
      },
      {
        title: "Study Security",
        subject: "human",
        category: "work",
        frequency: "1 day",
      },
      {
        title: "Learn New Skill",
        subject: "human",
        category: "work",
        frequency: "1 week",
      },
      {
        title: "Finish Project Ticket",
        subject: "human",
        category: "work",
        frequency: "1 day",
      },
      {
        title: "Test New Feature",
        subject: "human",
        category: "work",
        frequency: "1 day",
      },
      {
        title: "Deploy Application",
        subject: "human",
        category: "work",
        frequency: "1 week",
      },
    ],
  },
  {
    title: "Adventure & Travel",
    emoji: "✈️",
    description: "Planning, packing, trips, Disneyland, family photos, and memories.",
    presets: [
      {
        title: "Plan Adventure",
        subject: "human",
        category: "adventure",
        frequency: "1 week",
      },
      {
        title: "Research Destination",
        subject: "human",
        category: "adventure",
        frequency: "1 week",
      },
      {
        title: "Pack for Trip",
        subject: "human",
        category: "adventure",
        frequency: "1 mon",
      },
      {
        title: "Book Travel",
        subject: "human",
        category: "adventure",
        frequency: "1 mon",
      },
      {
        title: "Visit Disneyland",
        subject: "human",
        category: "adventure",
        frequency: "1 mon",
      },
      {
        title: "Explore New Place",
        subject: "human",
        category: "adventure",
        frequency: "1 week",
      },
      {
        title: "Take Family Photo",
        subject: "human",
        category: "family",
        frequency: "1 week",
      },
      {
        title: "Create Travel Memory",
        subject: "human",
        category: "family",
        frequency: "1 week",
      },
    ],
  },
  {
    title: "Family & Relationships",
    emoji: "❤️",
    description: "Connection, encouragement, events, reading, and good news.",
    presets: [
      {
        title: "Call Family Member",
        subject: "human",
        category: "family",
        frequency: "1 week",
      },
      {
        title: "Check on Friend",
        subject: "human",
        category: "family",
        frequency: "1 week",
      },
      {
        title: "Send Encouragement",
        subject: "human",
        category: "family",
        frequency: "1 week",
      },
      {
        title: "Plan Family Activity",
        subject: "human",
        category: "family",
        frequency: "1 week",
      },
      {
        title: "Read with Child",
        subject: "human",
        category: "family",
        frequency: "1 day",
      },
      {
        title: "Attend Event",
        subject: "human",
        category: "family",
        frequency: "1 week",
      },
      {
        title: "Share Good News",
        subject: "human",
        category: "family",
        frequency: "1 week",
      },
    ],
  },
  {
    title: "Fun Random Tasks",
    emoji: "🎲",
    description: "Small chaotic quests likely to produce excellent pet commentary.",
    presets: [
      {
        title: "Acquire Coffee",
        subject: "human",
        category: "wellness",
        frequency: "1 day",
      },
      {
        title: "Touch Grass",
        subject: "human",
        category: "wellness",
        frequency: "1 day",
      },
      {
        title: "Stop Doomscrolling",
        subject: "human",
        category: "wellness",
        frequency: "1 day",
      },
      {
        title: "Put Phone Down",
        subject: "human",
        category: "wellness",
        frequency: "1 day",
      },
      {
        title: "Hydrate Human",
        subject: "human",
        category: "hydration",
        frequency: "4 hours",
      },
      {
        title: "Organize Chaos",
        subject: "human",
        category: "household",
        frequency: "1 week",
      },
      {
        title: "Defeat Laundry Monster",
        subject: "human",
        category: "household",
        frequency: "1 week",
      },
      {
        title: "Conquer Paper Pile",
        subject: "human",
        category: "household",
        frequency: "1 week",
      },
      {
        title: "Hunt Missing Item",
        subject: "human",
        category: "adventure",
        frequency: "1 week",
      },
      {
        title: "Celebrate Small Victory",
        subject: "human",
        category: "family",
        frequency: "1 day",
      },
    ],
  },
  {
    title: "Dog Missions",
    emoji: "🐕",
    description: "Patrols, walks, training, social calls, and security sweeps.",
    presets: [
      {
        title: "Neighborhood Patrol",
        subject: "pet",
        category: "adventure",
        frequency: "1 day",
        species: ["dog"],
      },
      {
        title: "Walk the Human",
        subject: "pet",
        category: "walk",
        frequency: "1 day",
        species: ["dog"],
      },
      {
        title: "Visit Dog Park",
        subject: "pet",
        category: "adventure",
        frequency: "1 week",
        species: ["dog"],
      },
      {
        title: "Chase Ball",
        subject: "pet",
        category: "play",
        frequency: "1 day",
        species: ["dog"],
      },
      {
        title: "Practice Good Behavior",
        subject: "pet",
        category: "wellness",
        frequency: "1 day",
        species: ["dog"],
      },
      {
        title: "Meet New Friends",
        subject: "pet",
        category: "family",
        frequency: "1 week",
        species: ["dog"],
      },
      {
        title: "Investigate Strange Noises",
        subject: "pet",
        category: "household",
        frequency: "1 day",
        species: ["dog"],
      },
      {
        title: "Security Sweep",
        subject: "pet",
        category: "household",
        frequency: "1 day",
        species: ["dog"],
      },
    ],
  },
  {
    title: "Cat Missions",
    emoji: "🐈",
    description: "Surveillance, sunbeam operations, critter watch, and box research.",
    presets: [
      {
        title: "Refill Water Bowl",
        subject: "pet",
        category: "household",
        frequency: "1 day",
        species: ["cat"],
      },
      {
        title: "Scoop Litter Box",
        subject: "pet",
        category: "household",
        frequency: "1 day",
        species: ["cat"],
      },
      {
        title: "Open Patrol Routes",
        subject: "pet",
        category: "household",
        frequency: "1 day",
        species: ["cat"],
      },
      {
        title: "Bird Surveillance",
        subject: "pet",
        category: "play",
        frequency: "1 day",
        species: ["cat"],
      },
      {
        title: "Window Monitoring",
        subject: "pet",
        category: "household",
        frequency: "1 day",
        species: ["cat"],
      },
      {
        title: "Sunbeam Occupation",
        subject: "pet",
        category: "wellness",
        frequency: "1 day",
        species: ["cat"],
      },
      {
        title: "Critter Watch",
        subject: "pet",
        category: "play",
        frequency: "1 day",
        species: ["cat"],
      },
      {
        title: "Front Door Patrol",
        subject: "pet",
        category: "household",
        frequency: "1 day",
        species: ["cat"],
      },
      {
        title: "Nap Quality Assurance",
        subject: "pet",
        category: "wellness",
        frequency: "1 day",
        species: ["cat"],
      },
      {
        title: "Countertop Inspection",
        subject: "pet",
        category: "household",
        frequency: "1 day",
        species: ["cat"],
      },
      {
        title: "Cardboard Box Exploration",
        subject: "pet",
        category: "adventure",
        frequency: "1 week",
        species: ["cat"],
      },
    ],
  },
  {
    title: "Bird Missions",
    emoji: "🐦",
    description: "Tree claims, morning songs, seed logistics, nest upkeep, and airspace patrols.",
    presets: [
      {
        title: "Claim Tree Territory",
        subject: "pet",
        category: "adventure",
        frequency: "1 day",
        species: ["bird"],
      },
      {
        title: "Morning Song Practice",
        subject: "pet",
        category: "wellness",
        frequency: "1 day",
        species: ["bird"],
      },
      {
        title: "Seed Collection",
        subject: "pet",
        category: "household",
        frequency: "1 day",
        species: ["bird"],
      },
      {
        title: "Nest Maintenance",
        subject: "pet",
        category: "household",
        frequency: "1 week",
        species: ["bird"],
      },
      {
        title: "Airspace Patrol",
        subject: "pet",
        category: "adventure",
        frequency: "1 day",
        species: ["bird"],
      },
    ],
  },
  {
    title: "Fish Missions",
    emoji: "🐠",
    description: "Bubble audits, tank patrols, and imaginary ocean expeditions.",
    presets: [
      {
        title: "Bubble Inspection",
        subject: "pet",
        category: "wellness",
        frequency: "1 day",
        species: ["fish"],
      },
      {
        title: "Coral Reef Tour",
        subject: "pet",
        category: "adventure",
        frequency: "1 week",
        species: ["fish"],
      },
      {
        title: "Tank Patrol",
        subject: "pet",
        category: "household",
        frequency: "1 day",
        species: ["fish"],
      },
      {
        title: "Ocean Exploration Simulation",
        subject: "pet",
        category: "adventure",
        frequency: "1 day",
        species: ["fish"],
      },
    ],
  },
  {
    title: "Horse Missions",
    emoji: "🐴",
    description: "Trail rides, pasture checks, carrots, grooming, and freedom protocols.",
    presets: [
      {
        title: "Trail Ride",
        subject: "pet",
        category: "adventure",
        frequency: "1 week",
        species: ["horse"],
      },
      {
        title: "Pasture Check",
        subject: "pet",
        category: "household",
        frequency: "1 day",
        species: ["horse"],
      },
      {
        title: "Carrot Appreciation",
        subject: "pet",
        category: "wellness",
        frequency: "1 day",
        species: ["horse"],
      },
      {
        title: "Fence Inspection",
        subject: "pet",
        category: "household",
        frequency: "1 week",
        species: ["horse"],
      },
      {
        title: "Grooming Session",
        subject: "pet",
        category: "wellness",
        frequency: "1 week",
        species: ["horse"],
      },
      {
        title: "Scenic Walkabout",
        subject: "pet",
        category: "movement",
        frequency: "1 day",
        species: ["horse"],
      },
      {
        title: "Open Field Moment",
        subject: "pet",
        category: "adventure",
        frequency: "1 week",
        species: ["horse"],
      },
    ],
  },
  {
    title: "Highland Cow Missions",
    emoji: "🐄",
    description: "Pasture wisdom, grass audits, sky watching, and gentle encouragement.",
    presets: [
      {
        title: "Meadow Appreciation",
        subject: "pet",
        category: "wellness",
        frequency: "1 day",
        species: ["cow", "highland cow", "virtual pet"],
      },
      {
        title: "Grass Quality Inspection",
        subject: "pet",
        category: "household",
        frequency: "1 day",
        species: ["cow", "highland cow", "virtual pet"],
      },
      {
        title: "Cloud Observation",
        subject: "pet",
        category: "wellness",
        frequency: "1 day",
        species: ["cow", "highland cow", "virtual pet"],
      },
      {
        title: "Philosophical Reflection",
        subject: "pet",
        category: "wellness",
        frequency: "1 day",
        species: ["cow", "highland cow", "virtual pet"],
      },
      {
        title: "Encourage Human Wellness",
        subject: "pet",
        category: "family",
        frequency: "1 day",
        species: ["cow", "highland cow", "virtual pet"],
      },
    ],
  },
];
